### PR TITLE
Update hello-version to 2.12.1 from 2.12

### PR DESCRIPTION
**Pull request by zosopentoolsmain**

### CODE REVIEW

**Comment by HarithaIBM** [comment]
Build failing at hello.doc. Comparing previous version and new version. Seeing changes in doc folder. Issue is still under analysis

**Comment by IgorTodorovskiIBM** [comment]
Pushed in a change to add xz as a dependency and also changed the default build line to stable

**Comment by IgorTodorovskiIBM** [comment]
Looks like the checks passed, will merge it in

**Pull request merged**
